spring:
  application:
    name: spring-boot-2.0.1-reactive
  datasource:
    url: jdbc:mysql://localhost:3306/github?useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect